from __future__ import annotations

import os
import re
import sys
import subprocess
from pathlib import Path
from typing import List, Tuple


# ============================================================
# Batch run configuration
# ============================================================
CSV_NAMES: List[str] = [
    # "Positive_Negative_balanced_25366.csv",
    "Points_China_all_10km.csv",
]

SSP_LIST: List[str] = ["ssp1", "ssp3", "ssp5"]

# True:
# False: ,
STOP_ON_ERROR = False


# ============================================================
# Processing step.
# ============================================================
def build_combinations() -> List[Tuple[str, str]]:
    """Generates 2 × 3 = 6 sets of (csv_name, ssp) combinations."""
    return [(csv_name, ssp) for csv_name in CSV_NAMES for ssp in SSP_LIST]



def replace_df_path_block(script_text: str, csv_name: str) -> str:
    """df_path = os.path.join(...) . , os.path.join ."""
    pattern = re.compile(
        r"df_path\s*=\s*os\.path\.join\(\n[\s\S]*?\n\)",
        flags=re.MULTILINE,
    )

    replacement = (
        'df_path = os.path.join(\n'
        '    input_folder_path, "points",\n'
        f'    "{csv_name}"\n'
        ')'
    )

    new_text, n = pattern.subn(replacement, script_text, count=1)
    if n != 1:
        raise RuntimeError("Unable to uniquely match the df_path = os.path.join(...) code block, please check the main script format.")
    return new_text



def replace_ssp_line(script_text: str, ssp: str) -> str:
    """ssp = "..." ."""
    pattern = re.compile(r'^ssp\s*=\s*["\'][^"\']+["\'].*$', flags=re.MULTILINE)
    replacement = f'ssp = "{ssp}" # Automatically written by batch script'

    new_text, n = pattern.subn(replacement, script_text, count=1)
    if n != 1:
        raise RuntimeError("Unable to uniquely match the line ssp = ..., please check the main script format.")
    return new_text



def build_temp_script(main_script_path: Path, csv_name: str, ssp: str, temp_dir: Path) -> Path:
    """Generate a single-run temporary script based on the original Main_function_Feature_Extract.py."""
    script_text = main_script_path.read_text(encoding="utf-8")
    script_text = replace_df_path_block(script_text, csv_name)
    script_text = replace_ssp_line(script_text, ssp)

    safe_csv_stem = Path(csv_name).stem
    temp_script_path = temp_dir / f"__tmp__Main_function_Feature_Extract__{safe_csv_stem}__{ssp}.py"
    temp_script_path.write_text(script_text, encoding="utf-8")
    return temp_script_path



def cleanup_temp_scripts(script_dir: Path) -> None:
    """Delete all temporary scripts generated by this batch script in the current directory."""
    temp_files = sorted(script_dir.glob("__tmp__Main_function_Feature_Extract__*.py"))
    if not temp_files:
        return

    for temp_file in temp_files:
        try:
            temp_file.unlink()
            print(f"[Clean] Temporary scripts removed:{temp_file.name}")
        except Exception as exc:
            print(f"[] :{temp_file} | {exc}")



def run_one_case(
    python_executable: str,
    main_script_dir: Path,
    temp_script_path: Path,
    csv_name: str,
    ssp: str,
    log_dir: Path,
) -> int:
    """Execute a set of combinations and write stdout/stderr to the log file."""
    log_name = f"{Path(csv_name).stem}__{ssp}.log"
    log_path = log_dir / log_name

    print("\n" + "=" * 100)
    print(f"Start execution: csv={csv_name} | ssp={ssp}")
    print(f":{temp_script_path.name}")
    print(f"Log file:{log_path}")
    print("=" * 100)

    env = os.environ.copy()
    old_pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (
        str(main_script_dir)
        if not old_pythonpath
        else str(main_script_dir) + os.pathsep + old_pythonpath
    )

    with log_path.open("w", encoding="utf-8") as log_file:
        log_file.write(f"[Batch] csv_name   = {csv_name}\n")
        log_file.write(f"[Batch] ssp        = {ssp}\n")
        log_file.write(f"[Batch] script     = {temp_script_path.name}\n")
        log_file.write(f"[Batch] PYTHONPATH = {env['PYTHONPATH']}\n\n")
        log_file.flush()

        completed = subprocess.run(
            [python_executable, str(temp_script_path)],
            cwd=str(main_script_dir),
            env=env,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            text=True,
            check=False,
        )

    if completed.returncode == 0:
        print(f": csv={csv_name} | ssp={ssp}")
    else:
        print(f"Execution failed: csv={csv_name} | ssp={ssp} | returncode={completed.returncode}")
        print(f":{log_path}")

    return completed.returncode


# ============================================================
# Main program
# ============================================================
def main() -> None:
    script_dir = Path(__file__).resolve().parent
    main_script_path = script_dir / "Main_function_Feature_Extract.py"

    if not main_script_path.exists():
        raise FileNotFoundError(
            f"Main script not found:{main_script_path}\n"
            f"Main_function_Feature_Extract.py ."
        )

    # ,
    temp_dir = script_dir
    log_dir = script_dir / "_batch_logs"
    log_dir.mkdir(exist_ok=True)

    # First clean up the temporary scripts left in history
    cleanup_temp_scripts(script_dir)

    combinations = build_combinations()
    print(f"will execute the following{len(combinations)}Group combination:")
    for i, (csv_name, ssp) in enumerate(combinations, start=1):
        print(f"  {i}. {csv_name} | {ssp}")

    failed_cases: List[Tuple[str, str, int]] = []

    try:
        for csv_name, ssp in combinations:
            temp_script_path = build_temp_script(main_script_path, csv_name, ssp, temp_dir)

            try:
                returncode = run_one_case(
                    python_executable=sys.executable,
                    main_script_dir=script_dir,
                    temp_script_path=temp_script_path,
                    csv_name=csv_name,
                    ssp=ssp,
                    log_dir=log_dir,
                )
            finally:
                # Delete the corresponding temporary script immediately after each group is finished running
                try:
                    if temp_script_path.exists():
                        temp_script_path.unlink()
                        print(f"[Clean] Temporary scripts removed:{temp_script_path.name}")
                except Exception as exc:
                    print(f"[] :{temp_script_path} | {exc}")

            if returncode != 0:
                failed_cases.append((csv_name, ssp, returncode))
                if STOP_ON_ERROR:
                    break
    finally:
        # Clean everything up to prevent any residue after abnormal interruption
        cleanup_temp_scripts(script_dir)

    print("\n" + "#" * 100)
    print("Batch operation ends")
    print(f"Log directory:{log_dir}")

    if failed_cases:
        print("The following combination failed to execute:")
        for csv_name, ssp, returncode in failed_cases:
            print(f"  - {csv_name} | {ssp} | returncode={returncode}")
        raise SystemExit(1)
    else:
        print(f"All{len(combinations)}The group combination was executed successfully.")
        raise SystemExit(0)


if __name__ == "__main__":
    main()
